Mysql:
  user: root
  passcode: root
  database: mc_nancheng
  host: localhost
  port: 3306
  table: Gang

#工会设置
GangSetting:
  #战斗力计算公式,该公式意思为 工会等级x2 + 5为战斗力总和
  #目前仅支持
  #%level% 公会等级
  #%members% 公会成员
  #%ownerlevel% 会长等级
  value: (%level% * 2) + 5
  #初始帮派等级
  initLevel: 1
  #初始帮派资金
  initMoney: 100
  #支持绑定
  RuleLore: "&a已绑定"